(DOCSP-43346) Auditing and Logging
mongodb/docs-atlas-architecture pull request #33
Opened 2024-11-04 04:46 UTC by JuliaMongo

DOCSP-

Staging

2024-11-05 22:00 UTC, lmkerbey-mdb requested changes

2024-11-05 22:00 UTC, lmkerbey-mdb commented on source/auditing-logging.txt
> +<audit-action-details-results>`.
```suggestion
want to audit. You can configure manual :manual:`auditing </core/auditing>` 
of most of the documented :manual:`system event actions 
<audit-action-details-results>` in |service|.
```
This reads more naturally to me.

2024-11-05 22:00 UTC, lmkerbey-mdb commented on source/auditing-logging.txt
> +- timestamps for successful and failed attempts.
Database users and IP addresses are not, themselves, authentication events, right? There are authentication events which pertain to them, though. Are the recorded events database user login attempts and connection attempts from IP addresses? I think we should either stick with the characterization 'events' and then find a way to rewrite these items to be events, or we rework the wording above to say something like 'record authentication events, including those pertaining to:'

2024-11-05 22:00 UTC, lmkerbey-mdb commented on source/auditing-logging.txt
> +of examples, see :manual:`MongoDB auditing </core/auditing>`.
RE: the above, consulting this list might be a good way to get an idea of how we can rewrite the list to describe events.

2024-11-08 06:21 UTC, lantoli approved these changes

2024-11-08 09:57 UTC, fmenezes approved these changes

2024-11-08 18:33 UTC, lmkerbey-mdb requested changes

2024-11-08 18:33 UTC, lmkerbey-mdb commented on source/auditing-logging.txt
> +        by running the following command in the terminal:
```suggestion
        paying organization. Store your public and private keys as environment 
        variables by running the following command in the terminal: 
```

2024-11-10 01:46 UTC, lmkerbey-mdb approved these changes
LGTM

2024-11-10 02:56 UTC, merged